### ISSUE TITLE
Valet and custom keychain file?

### ISSUE THREAD

**Issue by cheizer** [square/Valet#101]
Hello,
Can Valet use a custom keychain file on Mac OS X?

Thanks!

**Comment by dfed** [comment]
Thanks for your interest in Valet! Unfortunately, custom keychain files aren't something we currently support (or have plans to support). I'm guessing you're trying to import data from an existing keychain that isn't the main one into Valet? To accomplish that, you'll need to migrate the existing keychain into the main keychain first.

Closing this out since this isn't on our roadmap.
