### ISSUE TITLE
How can I configure valet to pass ATS?

### ISSUE THREAD

**Issue by seekcx** [square/Valet#117]

**Comment by dfed** [comment]
What is ATS? What about Valet is not passing it right now? What kind of Valet are you using? Do you have a link to ATS documentation?

Without significantly more detail we won’t be able to help.

**Comment by seekcx** [comment]
hi @dfed, Thank you for answering me.

ATS (App Transport Security)，iOS will force it to verify it. Cause I can not call the service on valet.

**Comment by dfed** [comment]
App Transport Security is a networking layer. Valet doesn’t interact with the network.

Do you have sample code? A link to documentation explaining what exactly you are trying to accomplish?

My gusss is Valet isn’t the problem here. But I don’t understand what you’re trying to do so I can’t say that definitively.

**Comment by seekcx** [comment]
Yeah, I should ask how to configure SSL certificates for domains? Does valet have any configuration?

**Comment by dfed** [comment]
Sounds like you’re trying to use Valet for `kSecClassCertificate` values. Valet currently only supports `kSecClassGenericPassword`. We don’t have Certificate handling on our roadmap right now, but we’ll consider it. Closing this out.
