### ISSUE TITLE
Document that Shared Access Group Identifier shouldn't contain Bundle Seed ID

### ISSUE THREAD

**Issue by LinusU** [square/Valet#130]
Just spent a few hours tracking down the dreaded `errSecMissingEntitlement` error, and in the end, it turned out that my problem was that I had added the Bundle Seed ID/App Identity Prefix. Valet actually is being _smart_ and figures out and adds that ID automatically.

It would be nice if 1) it could be added to the documentation, and 2) maybe if the string passed already starts with the same ID that is detected, we could error out or print a warning for the developer.

Thanks for a great lib 🍻

**Comment by dfed** [comment]
Oh no! Apologies for sending you on a wild goose chase, and thank you for letting us know we did! Since we already provide an example that shows creating a shared access group Valet without the bundle seed ID, I think asserting that the ID isn't given as a prefix to the identifier is worthwhile. PR will be up shortly.
