### ISSUE TITLE
Cannot access data in App Group

### ISSUE THREAD

**Issue by MarkVillacampa** [square/Valet#138]
Using an App Group identifier is an alternative to using a Keychain Sharing identifier to share keychain items between apps.

While Keychain Sharing identifiers are prefixed by the team prefix id, App Groups are prefixed by `group.`.

Valet adds the team prefix id  to all identifiers, which means it's not possible to use an App Group:

https://github.com/square/Valet/blob/master/Sources/Internal/Service.swift#L55

Could someone confirm wether I am missing something?

**Comment by dfed** [comment]
@MarkVillacampa I think you're right. Valet uses Keychain Sharing rather than App Groups for sharing data between applications + extensions made by the same developer. I haven't played with App Groups much before: are there concrete benefits to it vs Keychain Sharing?

Hopefully you can migrate your keychain values into a `sharedAccessGroupValet` & add the keychain sharing entitlement to get things working with Valet?

I wonder if we should allow for using App Groups in addition to Keychain Sharing. First I need to understand the differences though. If you could share any documentation on App Groups that you love, that'd be super helpful.

**Comment by MarkVillacampa** [comment]
App Groups are used generally to let multiple apps share access to a group container via `NSFileManager`.

https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW19

Additionally, the `com.apple.security.application-groups` entitlement extends the `keychain-access-groups` entitlement:

> Application Groups. When you collect related apps into an application group using the application-groups entitlement, they share access to a group container, and gain the ability to message each other in certain ways, as described in Adding an App to an App Group. Starting is iOS 8, the array of strings given by this entitlement also extends the list of keychain access groups.

https://developer.apple.com/library/content/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html#//apple_ref/doc/uid/TP30000897-CH204-SW1

In practice, I've seen apps with both entitlements, no idea which identifier they actually use in their code.

The only difference I see is Keychain Groups give access to any app under your development team to access the data, whereas App Groups give access only to apps belonging to that specific group.

**Comment by dfed** [comment]
Since I haven't heard back since April, I'm going to close this out. I'll happily re-open if more actionable information is provided.
