### ISSUE TITLE
Differentiate between errSecUserCanceled and errSecAuthFailed

### ISSUE THREAD

**Issue by umbri** [square/Valet#143]
Thank you for sharing this.

I think that ```errSecUserCanceled``` and ```errSecAuthFailed``` are 2 different important errors and grouping them in one like ```userCancelled``` is not the right way, my propose is to split them in ```userCancelled``` and ```authFailed```, ref: #144 

Thank you

**Comment by dfed** [comment]
@umbri thanks for the issue and pull request!

We currently conflate these errors because both `authFailed` and` userCancelled` are triggered by events that effectively mean that the user cancelled. `authFailed` is returned when the user failed to input their password or locked the screen while you were prompting for their password – I wouldn't want our library's customers to have to think about the difference between these a user failing to enter a password and hitting cancel, since they are effectively the same thing. When you get the `userCancelled` return, you know there is valid data in the keychain, but that the user didn't let you access it.

https://github.com/square/Valet/pull/73#issuecomment-184892249 is where we originally discussed treating both `errSecUserCanceled` and `errSecAuthFailed` as `userCancelled`. If you disagree with that logic, it'd be great to hear why. I'd also be curious what use-cases having separate errors for `authFailed` vs` userCancelled` will enable.

**Comment by dfed** [comment]
Got it. Interesting! Given that `errSecAuthFailed` can be returned when a user accidentally hits the power button, I'd be careful deleting all data when you get that error code.

I need to sit on this use case a bit. I'm not a huge fan of exposing authorization failure as a separate `case` from `userCancelled`, since in almost all cases they're the same. I'm thinking about maybe adding an additional flag as associated data on `userCancelled` (i.e. `case userCancelled(dueToAuthorizationFailure: Bool)`. Adding an associated value would be a non-breaking change for existing clients who use `switch` statements without a `default`, and allows us to keep the simple flow for the majority use case. I like the associated data approach better, but I'm still not convinced that this is something that our library wants to expose – a guiding tenant of our library is to make the keychain exceptionally simple to use, which means limiting API surface.

@EricMuller22, any thoughts?

**Comment by umbri** [comment]
@dfed I like ```userCancelled(dueToAuthorizationFailure: Bool)``` too

**Comment by gfontenot** [comment]
I haven't been involved in this project for long, so my opinions here shouldn't necessarily take precedence over other people's, but:

I think I'd question if this lib is "for" people building a password manager. It seems like we should focus our design towards people who aren't trying to make keychain access a core competency of their app. A password manager almost certainly would require keychain access as a core competency, and so will have different feature requirements as a result. I'd be wary of adopting support for lower level features that aren't going to be needed/used by our target demographic.

**Comment by dfed** [comment]
> I think I'd question if this lib is "for" people building a password manager. It seems like we should focus our design towards people who aren't trying to make keychain access a core competency of their app.

Very well said. Thank you for the sanity check.

I'm going to close this out as Won't Fix. But if we get enough folks asking for this, I can see us reconsidering.
