### ISSUE TITLE
LegacyValet build errors using SPM in Xcode 11

### ISSUE THREAD

**Issue by msaps** [square/Valet#185]
When building Valet using SPM in Xcode 11, the project fails to build for watchOS and tvOS. It looks as though `LegacyValet` doesn't build properly on the platforms, and this is specified as a target to build in the `Package.swift`. This is reproducible in the `xcodeproj` by attempting to build the `LegacyValet` project on both watchOS and tvOS.

watchOS:
<img width="1512" alt="Screenshot 2019-09-21 at 20 28 23" src="https://user-images.githubusercontent.com/3515448/65377611-b88a4380-dcae-11e9-83a9-4b5b0d8d4e5d.png">

tvOS:
<img width="1512" alt="Screenshot 2019-09-21 at 20 28 32" src="https://user-images.githubusercontent.com/3515448/65377612-be802480-dcae-11e9-94e1-77f50221f269.png">

**Comment by dfed** [comment]
Thank you for the report! You're absolutely right that `LegacyValet` isn't built for watchOS or tvOS. I'm surprised that `LegacyValet` is being built as part of the `Valet` product, since it isn't listed as a target of the Valet product:
```
    products: [
        .library(
            name: "Valet",
            targets: ["Valet"]),
    ],
```

Looking into this now. May need to remove `LegacyValet` from the Package entirely. That target is only used in an integration test by the manually managed Xcode project to ensure backwards compatibility, so it shouldn't be problematic to remove it. It was never intended to be part of the built Valet product.

**Comment by dfed** [comment]
@msaps 3.2.7 should work for you!

**Comment by msaps** [comment]
@dfed works great - thanks a lot!! 🚀
