### ISSUE TITLE
Migrating from xcode 11.1 to 11.3

### ISSUE THREAD

**Issue by vijay-natarajan** [square/Valet#217]
When i tried to run the project in xcode 11.3,
I get compilation error “module compiled in swift 5.1 cannot be imported by swift 5.1.3 compiler”
Any idea how to rectify this issue???

**Comment by dfed** [comment]
Some questions:

1. What version of Valet are you running?
1. How are you integrating Valet into your project? 
1. Are you using this integration system with other third-party libraries?
1. Have you had this issue with any other third party library?

**Comment by vijay-natarajan** [comment]
1. I use version 5.2.6
2. I actually use static framework method (first run the valet xcode proj from master and the i open the directory of ios frameworks and the embed that framework into your project). As i need only valet ios framework  and i dont want to use whole valet bundle i chose this method
3. No.
4. No

I found what is the problem . As i created static framework that will work only on swift 5.1 . If i want to use valet on 5.3.1 i should again create static framework and embed  that framework again. I did this method ,now i got error in internal/keychain line number 91.swift in which it unable to set .
What is the solution??

**Comment by dfed** [comment]
> I use version 5.2.6

I'm slightly confused, since that isn't a valid version of Valet. I'm assuming you meant 3.2.6.

> I actually use static framework method (first run the valet xcode proj from master and the i open the directory of ios frameworks and the embed that framework into your project). As i need only valet ios framework and i dont want to use whole valet bundle i chose this method

You can integrate Valet using CocoaPods, Carthage, or Swift Package Manager, and all of them will only include the iOS framework if that's all you need. You don't need to run these steps yourself.

> I did this method ,now i got error in internal/keychain line number 91.swift in which it unable to set .
What is the solution??

If you're referring to [this line](https://github.com/square/Valet/blob/master/Sources/Valet/Internal/Keychain.swift#L91), the error says you're setting an empty value. The keychain can only store values of non-zero length.

Since the initial issue has been resolved, I'm closing this issue. If you have further issues, please open a new issue.
