### ISSUE TITLE
Integer in Valet

### ISSUE THREAD

**Issue by martino-dot** [square/Valet#225]
I am currently trying to use an integer value with Valet. This is because the user's id is an integer and if I set it as string it just displays as nil because in the JSON it shows up as an int. How can I use Valet to save an integer?

**Comment by dfed** [comment]
Thanks for your interest in Valet! In the future, please include some sample code when filing issues to make it more clear what you’re trying to do.

As is, I don’t fully understand what you’re referring to when you say that “it just displays nil because in the JSON it shows up as an int”. My guess, though, is you’d have success if you explicitly converted your Int to Data (maybe using a Codable object with a JSONEncoder/Decoder?), and tried setting and retrieving a data object rather than a string.

Valet doesn’t have opinions on what kind of data you can store – whatever data you give to Valet, Valet stores without modification. Valet will concert a String to Data for you if you use the String methods, but since you are trying to persist an Int I wouldn’t recommend using the String methods.

I think this question isn’t specific to Valet, but is rather a general question about Int <-> Data conversión in Swift or Objective-C. As such, I’m closing this issue. Let me know if you think I missed something.
