### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by colemcampbell** [square/Valet#251]
One problem I'm running into with Valet is the fact that it doesn't namespace the various types that it includes, such as Identifier, Accessibility, and KeychainError. I think that if possible, it would be preferable to nest them as Valet.Identifier, etc, so that Valet doesn't pollute the global scope of the project it is imported into.

**Comment by dfed** [comment]
Thank you for the feedback @colemcampbell!

I can add this request to the Valet 5 wishlist. Since changing the namespace would be a breaking change, this isn't something we'd be able to support in this release.

The good news is that in the interim, it'd be easy to maintain a fork that wrapped our types in a namespace of your choosing.

To help me understand the scope of the problem: does the namespace issue occur only in files that import Valet? Or is it any module that links against Valet?

**Comment by dfed** [comment]
It's been a few years and I haven't heard back, nor has this issue received any +1s. I'm closing this issue since this request does not seem terribly popular. If you are reading this and think this request was reasonable, please answer the above scoping question and reopen this issue.
