### ISSUE TITLE
Tips on building and running the sample app?

### ISSUE THREAD

**Issue by perlguy99** [square/Valet#272]
I'm trying to build and run the sample app but I am running into all sorts of issues with signing.  Does anyone have any tips on how to actually get this running on a device?

**Comment by dfed** [comment]
Hi @perlguy99! Thanks for your interest in Valet and sorry you're running into trouble with the `ValetTouchIDTest` target.

We don't have instructions for how to get this project running on a device – this project was initially intended to aid me in my ability to test TouchID while we were first developing the feature 😅. You're right there are a few gotchas to getting this running with your own certificates. Running on device (unlike the simulator) requires code-signing which introduces a few fun complications.

To get the sample project running, you'll need to follow steps similar to [our steps for getting unit tests running locally on macOS](https://github.com/square/Valet/blob/master/Contributing.md#testing-changes-on-macos). Basically you'll need to change the bundle ID to a custom ID, and change all the Team IDs to be your development team rather than my development team.

It might honestly be easier to copy the `ValetTouchIDTestViewController` class into a project you already have building on device and displaying that view controller from your existing project. Note that the `ValetTouchIDTest` app doesn't have any special signing capabilities.

I'm going to close this issue out, since getting `ValetTouchIDTest` running locally was never intended to be supported. But I hope I've given you enough information to unstick yourself. Feel free to respond below if you still need help – I'll still get notified even though this issue is closed.
