### ISSUE TITLE
tvOS target doesn't compile with Xcode 14.0 beta

### ISSUE THREAD

**Issue by diogot** [square/Valet#283]
It fails to compile with the error:

`'LAContext' is unavailable in tvOS`

We tested with beta 4 and beta 5 (the latest one at the moment).

**Comment by diogot** [comment]
It might be related to #270

**Comment by dfed** [comment]
Thanks for letting us know! And solid call-out that this issue is likely related to #270. Fixing this will likely require removing any `LAContext`-interacting code from the tvOS target. Technically this is a source-breaking change, but given that this source likely never worked to begin with [given the availability markings on `LAContext`](https://developer.apple.com/documentation/localauthentication/lacontext) we can likely fix this without a major version bump.

**Comment by diogot** [comment]
Awesome, thanks!
Let me know if you need any help.

**Comment by dfed** [comment]
If folk want a fast turnaround on this issue then I would encourage folk to put up a PR. I will not personally be addressing this issue this month.

**Comment by diogot** [comment]
It was an easy fix, I opened a PR #284 to fix this.
Let me know what do you think.

**Comment by diogot** [comment]
Should we close this issue now or wait until the fix goes in the next release?

**Comment by dfed** [comment]
I'll close this once I post a new release. Soon!

**Comment by dfed** [comment]
This is fixed on `master` in #284. After consulting with @NickEntin, I'm releasing this fix as a bug fix release with `4.1.3`. Our reasoning is we believe that `SinglePromptSecureEnclaveValet` never actually worked on `tvOS`, which means we expect no consumer of `Valet` is using it.

**If we are wrong and you did use this Valet type on a `tvOS` target, please let us know. I will never this change, push a bugfix version with the revert, and then un-revert this change and push a major version bump**

Thank you @diogot for both identifying and solving this issue!
