### ISSUE TITLE
[VALValet canAccessKeychain] spams the device log

### ISSUE THREAD

**Issue by omarkilani** [square/Valet#63]
Hey there,

Calling canAccessKeychain causes securityd and the calling process to spam the device log with messages about adding duplicates.

Every time it's called it prints about 4 messages to the log.

I see that this is some sort of "optimization":

https://github.com/square/Valet/blob/master/Valet/VALValet.m#L251

But IMHO I'm not seeing the real issue in calling containsObjectForKey. It probably spends more time logging the error than it would take to check the keychain.

IMHO2: canAccessKeychain isn't really something you call often since you know after launching/being unsuspended whether you're going to have access for that entire runloop (and can take out a background task assertion if you want to stay awake).

Is there something I'm missing? :)

**Comment by dfed** [comment]
Just ran a quick performance test. Writing `canAccessKeychain` as:
```objc
- (BOOL)canAccessKeychain;
{
    NSString *const canaryKey = @"VAL_KeychainCanaryUsername";
    NSString *const canaryValue = @"VAL_KeychainCanaryPassword";
    
    [self setString:canaryValue forKey:canaryKey];
    NSString *const retrievedCanaryValue = [self stringForKey:canaryKey];
    
    return [canaryValue isEqualToString:retrievedCanaryValue];
}
```

slows down performance of the method by 2x. On the Mac target on my machine average speed goes from ~0.034s to ~0.072s. Not to mention it leaves you open to some potentially nasty threading issues.

In order to avoid logging extraneously, setting a keychain item requires that you first check to see if the key/value pair already exists. If it exists, `SecItemUpdate`, if not, `SecItemAdd`. But we're testing if we can access the keychain, so testing to see if the pair already exists is equivalent to running `objectForKey:`, which we can't yet trust.

So maybe the better way to do this is try to short-circuit the manual `SecItemAdd` if we can.
```objc
- (BOOL)canAccessKeychain;
{
    __block BOOL canAccessKeychain = NO;
    VALExecuteBlockInLock(^{
        NSString *const canaryKey = @"VAL_KeychainCanaryUsername";
        NSString *const canaryValue = @"VAL_KeychainCanaryPassword";
        
        NSString *const retrievedCanaryValue = [self stringForKey:canaryKey];
        if ([canaryValue isEqualToString:retrievedCanaryValue]) {
            canAccessKeychain = YES;
            
        } else {
           // Canary value can't be found. Manually add the value to see if we can pull it back out.
            NSMutableDictionary *query = [self.baseQuery mutableCopy];
            [query addEntriesFromDictionary:[self _secItemFormatDictionaryWithKey:canaryKey]];
            query[(__bridge id)kSecValueData] = [canaryValue dataUsingEncoding:NSUTF8StringEncoding];
            (void)VALAtomicSecItemAdd((__bridge CFDictionaryRef)query, NULL);
            
            NSString *const retrievedCanaryValueAfterAdding = [self stringForKey:canaryKey];
            canAccessKeychain = [canaryValue isEqualToString:retrievedCanaryValueAfterAdding];
        }
        
    }, self.lockForSetAndRemoveOperations);
    
    return canAccessKeychain;
}
```

This makes the running `canAccessKeychain` nearly 2x slower (~0.06s) in the following cases:
- The very first time you call `canAccessKeychain` is called and you can access the keychain.
- The keychain is unaccessible access the keychain 

But the new code is 3x faster (~0.012s) after that first call when you can access. That's a trade-off that seems reasonable to me. It gets rid of the logging, and is only "slow" the first time it is called or when the app is in a bad state. Thoughts?

**Comment by omarkilani** [comment]
Hey Dan,

On a 6s running 9.2, the old code averages 2.8ms while the new code averages 1.2ms for the 'when you can access' case over 1 million calls running in the foreground. That seems pretty good to me.

**Comment by omarkilani** [comment]
If I change your conditional to this:

```objective-c
        if (__builtin_expect(([canaryValue isEqualToString:retrievedCanaryValue]), 1)) {
```

It runs a fair bit faster -- 0.9ms average over a million calls.

Not sure if you guys use likely/unlikely in your codebase though.

**Comment by dfed** [comment]
Saw the `__builtin_expect` after I put out the PR. Not sure I like the precedent of utilizing `__builtin_expect`... but that certainly is nifty. TIL!

Closing this issue out as I have a PR that addresses it.
