### ISSUE TITLE
get a persistent reference to the keychain item?

### ISSUE THREAD

**Issue by rsimenok** [square/Valet#77]
Hello, thank you for great lib!
How can i get a persistent reference to the keychain item?

**Comment by dfed** [comment]
Currently we don't expose persistent references. It may be possible for you to write an extension in your app on VALValet that'll let you do that, but I'm curious what your use case is. I'd wager that you don't need a persistent reference to get the job done.

**Comment by rsimenok** [comment]
I'm developing VPN application, where protocol variable requires persistent reference to the keychain item.
[passwordReference](https://developer.apple.com/library/ios/documentation/NetworkExtension/Reference/NEVPNProtocolClassRef/#//apple_ref/occ/instp/NEVPNProtocol/passwordReference)

Oh and also _"The keychain item must have the kSecClassGenericPassword class."_ - can i specify this?)

Thank you!

**Comment by dfed** [comment]
Oh dear. Let's start with the positive: all Valet key/value pairs are kSecClassGenericPassword.

But the downside is that Valet isn't built to expose these kinds of things. To do this, you'll need to basically copy/paste `objectForKey:options:status:` into an extension of your making. you'll need to modify it to return a persistent reference. Just add `kSecReturnPersistentRef : @YES` to the `query`. You'll get the reference data back. You can see how to use a persistent reference in our implementation of`migrateObjectsMatchingQuery:removeOnCompletion:`.

I don't think this kind of API belongs in Valet proper – the whole point of Valet is that it abstracts keychain insanity away from you. But if you want to be awesome open source your category under your name 🙂

I'm going to close this, since this is no longer really a Valet issue. But if you need keychain help please feel free to tweet at me (@thefederman)

**Comment by dfed** [comment]
And for the sake of being explicit: Make sure to call your copy/pasted `objectForKey:options:status` something else so it doesn't collide! `persistentDataForKey:` might be a good name :)

**Comment by rsimenok** [comment]
@dfed Got it! Many thanks for the help! :)
