### ISSUE TITLE
Valet breaks builds

### ISSUE THREAD

**Issue by antons** [square/Valet#78]
Valet has two methods which match the name, but not the return type of two common methods in Cocoa. 

```objc
- (BOOL)removeObjectForKey:(NSString *)key;
- (BOOL)removeAllObjects;
```

Foundation has 5 classes with these methods, and all of them share `void` return type. The difference breaks build in projects which invoke these methods on `id`. Xcode shows a compiler error: “Multiple methods named ‘removeObjectForKey:’ found with mismatched result, parameter type, or attributes”.

Objective-C generics help avoid the problem, and it’s trivial to modify Valet when using it in a project with conflicts. I do, however, think that Valet should avoid conflicts with established method signatures from Foundation. I understand that may not want to change this, and I just wanted to get this on your radar and find out what you think. 

Thank you for the work on Valet.

**Comment by dfed** [comment]
Valet never sends `removeObjectForKey:` to an unknown/`id` type, so it sounds like you're doing something wrong in your adoption of the project.

We don't have any plans to change the method names, since sending them to a `VALValet` instance shouldn't cause any build problems.

I'm going to close this out, but if you'd like further assistance please feel free to upload a sample project in the broken state – I'd be happy to take a look (that, and I'm quite curious how you got into this state). Or feel free to tweet at me `@TheFederman`.

**Comment by antons** [comment]
<img width="849" alt="screen shot 2016-06-07 at 09 17 40" src="https://cloud.githubusercontent.com/assets/129705/15847712/c094953e-2c90-11e6-86fa-edf0acd91ba7.png">

Here you go: [Valet.zip](https://github.com/square/Valet/files/301953/Valet.zip). You’ll see that  the compiler error goes away when “Valet” is excluded from the project: `#define VALET 0`.

**Comment by dfed** [comment]
Thanks for the example! IMO it's never good practice to send a message to an `id` whose type you don't know explicitly, and I strongly advocate for the use of generics when possible (and type checking -> casting when not possible).

If Valet means more developers adopt type-safe semantics, I think we've made the world a better place ;)
