### ISSUE TITLE
data stored in valet not cleared on app delete?

### ISSUE THREAD

**Issue by pcaruthers** [square/Valet#88]
I'm using Valet component with Xamarin;
it works well and is easy to use But ...

But - it seems that data stored in Valet persists even after the application has 
been deleted from the device.   I have 2 apps and use the shared data feature
so each app can know the other is on the device, but that data persists even
when the app has been deleted.   

Is this a bug or feature?  Is there some way to have the data removed 
when the application is removed?

**Comment by dfed** [comment]
Persistence after app deletion is a feature of Keychain. Keychain stores data even after the app is deleted – the Keychain is the only completely permanent storage system (short of wiping the iPhone) on iOS. There is no way to remove data when an application is removed. You can detect that an application has been removed by checking `canOpenURL` on a URL with the scheme the removed app supports and clean up in your other app that way.

If your app is uninstalled/reinstalled, you can detect this by checking to see if your NSUserDefaults have been removed (NSUserDefaults clear on app delete).

Since Valet is behaving correctly, I'm going to close this.

**Comment by pcaruthers** [comment]
thanks for the fast reply, i can make that work.
